//
// Created by Jaibeer Dugal on 05/11/2023.
//
// Enum of supported blurring algorithms

#ifndef CPPIMAGECOMPRESSION_ESUPPORTEDIMAGEBLURRINGALGOS_HPP
#define CPPIMAGECOMPRESSION_ESUPPORTEDIMAGEBLURRINGALGOS_HPP

enum ESupportedImageBlurringAlgos
{
    NAIVE_BLUR = 0,
    NAIVE_BLUR_THREADED,
    FAST_GAUSSIAN_BLUR,

};
#endif //CPPIMAGECOMPRESSION_ESUPPORTEDIMAGEBLURRINGALGOS_HPP
